### ISSUE TITLE
密码zym123456登不上去

### ISSUE THREAD

**Issue by liangfenggithub** [iteming/NodeTest#2]
请问默认用户名是什么“？

**Comment by iteming** [comment]
抱歉我应该把默认账号名和密码给清除了。
你把这两个加到 username  和 password里
username= zym	
password= e10adc3949ba59abbe56e057f20f883e

**Comment by liangfenggithub** [comment]
谢谢。在数据库中我增加了这两个字段的值，但是仍然提示密码错误，在源代码中我去掉了md5，可以登录了，具体原因还在研究中。
